name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: List available Xcode versions
        run: ls /Applications | grep Xcode

      - name: Set up Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.app/Contents/Developer

      - name: List available devices
        run: xcrun simctl list

      - name: Run Tests
        run: .github/workflows/run_tests.sh
